- stf_functional_tests.yml
The results of each test task will be written to that file as PASS or FAIL.
The file will be placed on undercloud machine and could be viewable from Jenkins job tree.
> Adding dedicated file for STF test results.

- roles/test_ha/README.md
- roles/test_ha/defaults/main.yml
- roles/test_ha/meta/main.yml
- roles/test_ha/tasks/main.yml
- roles/test_ha/vars/main.yml
- roles/test_snmpTraps/tasks/main.yml
1.Adding HA role and tests
2.Removing duplicate task from snmpTraps tests
> Adding HA role and tests

- roles/test_ha/tasks/main.yml
- stf_functional_tests.yml
Fixing indentation issue with HA tests
Adding pause module to HA tests
> Fixing indentation issue with HA tests

- .github/workflows/lint.yml
> [gha] Update checkout action to v3

- roles/client_side_tests/tasks/test_e2e.yml
- stf_functional_tests.yml
1.Removing unnecessary task from from stf_functional_tests
2. Fixing wrong ceph query
> Removing unnecessary task from from stf_functional_tests

- roles/test_sensubility/README.md
- roles/test_sensubility/defaults/main.yml
- roles/test_sensubility/meta/main.yml
- roles/test_sensubility/tasks/main.yml
- roles/test_sensubility/tasks/test_health_status.yml
- roles/test_sensubility/vars/main.yml
- stf_functional_tests.yml
1.Adding test for container down health status
2.Adding test for container up health status
> Adding role for collectd sensubility

- .zuul.yaml
update branch with new cvp changes
> Merge Master into Functional-alexy => update cvp jobs 

- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
- roles/test_observability_strategy/tasks/main.yml
- roles/test_sensubility/tasks/test_health_status.yml
- roles/test_verify_email/tasks/main.yml
Updated new polarion test IDs for stf functional tests
> Ayefimov stf fxn2

- .ansible-lint
- .zuul.yaml
- ci/ansible.cfg
- ci/patch.yaml
- ci/run_playbooks.yml
- ci/telemetry_autoscaling.yml
- ci/vars-functional-test.yml
- roles/telemetry_autoscaling/README.md
- roles/telemetry_autoscaling/defaults/main.yml
- roles/telemetry_autoscaling/meta/main.yml
- roles/telemetry_autoscaling/tasks/configure_heat.yml
- roles/telemetry_autoscaling/tasks/creating_stack.yml
- roles/telemetry_autoscaling/tasks/main.yml
- roles/telemetry_autoscaling/tasks/test_autoscaling.yml
- roles/telemetry_autoscaling/tasks/verify_autoscaling.yml
The role is imported from the infrawatch/telemetry_autoscaling repo. Moving it here will let us take advantage of zuul testing
> [telemetry_autoscaling] Add telemetry_autoscaling role and zuul job

- roles/telemetry_logging/README.md
- roles/telemetry_logging/meta/main.yml
- roles/telemetry_logging/tasks/journal_tests.yml
- roles/telemetry_logging/tasks/main.yml
Merge Main into Logging2 to pickup new telemetry_logging role addition.
> Add telemetry_logging role (#124)

- ci/run_playbooks.yml
its an enhancement to confirm the revert patch command.
The discussion : https://github.com/infrawatch/feature-verification-tests/pull/119#pullrequestreview-2171851815
> update the revert patch command

- .zuul.yaml
- callback_plugins/custom_logger.py
- ci/logging_tests_computes.yml
- ci/report_result.yml
- ci/vars-logging-test.yml
Add a job that runs the telemetry_logging role against an openstack cloud.
conflicts-with: https://github.com/infrawatch/feature-verification-tests/pull/142
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/141
> [zuul] Add logging job to run telemetry_logging test role

- roles/test_alerts/tasks/main.yml
> [test_alerts] Get prom_url and token before running test

- roles/test_sensubility/tasks/test_health_status.yml
Fixing RHELOSP-176036 and RHELOSP-176038
> Fixing RHELOSP-176036 and RHELOSP-176038

- roles/test_verify_email/tasks/main.yml
Fix for RHELOSP-176045 test_verify_email
> Fix for RHELOSP-176045 test_verify_email

- roles/test_sensubility/tasks/test_health_status.yml
Fixing RHELOSP-176036 and RHELOSP-176036
> Fixing RHELOSP-176036 and RHELOSP-176036

- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
- roles/test_metrics_retention/tasks/main.yml
- roles/test_sensubility/tasks/test_health_status.yml
- roles/test_snmp_traps/tasks/main.yml
- roles/test_verify_email/tasks/main.yml
Updated roles:
* test_alert
* test_snmp_trap
* test_metrics_retention
* test_sensubility
* test_verify_email
> Replace wc -l with stdout_lines | length

- roles/telemetry_graphing/tasks/cypress_test.yml
- roles/telemetry_graphing/tasks/verify_url.yml
Adding polarion TC IDs for graphing.
> Adding polarion TC IDs for graphing.

- roles/test_verify_email/tasks/main.yml
Delete the PrometheusRule and wait for it to be deleted
> [test_verify_email] Clean up the PrometheusRule post-test

- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
* Increase from 15 to 30 iterations of `oc delete pod ..`
> [test_alerts] Extend the time the sg-core is down for

- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
* Replace pause with a continuous check
* Extend the wait time, to account for latency
> [test_alerts] Replace pause with retry/until

- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
The task was marked incorrectly with a testcase ID. The testcase ID was for "Create the alert"
> [test_alerts] Remove duplicate testcase ID

- .zuul.yaml
- roles/common/README.md
- roles/telemetry_verify_metrics/README.md
- roles/telemetry_verify_metrics/defaults/main.yml
- roles/telemetry_verify_metrics/tasks/main.yml
- roles/telemetry_verify_metrics/tasks/verify_ceilometer_ipmi_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_kepler_metrics.yml
Closes: [OSPRH-11638 ](https://issues.redhat.com/browse/OSPRH-11638)
> Add metrics verification tasks for power monitoring components

- ci/logging_tests_controller.yml
Depends-On: https://github.com/openstack-k8s-operators/telemetry-operator/pull/621
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/217
> [ci] Add manifest tests to logging job

- roles/telemetry_verify_metrics/defaults/main.yml
- roles/telemetry_verify_metrics/tasks/main.yml
- roles/telemetry_verify_metrics/tasks/verify_ksm_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_node_exporter_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_podman_exporter_metrics.yml
* Add test for health monitoring feature
* Disable RBAC for KSM metrics
> Add test for health monitoring feature (#234)

- .zuul.yaml
* Update files list in zuul.yaml to be in the project
> [Zuul] Update files_list to be in the project (#240)

- ci/vars/osp18_env.yml
- roles/telemetry_verify_metrics/tasks/main.yml
- roles/telemetry_verify_metrics/tasks/verify_kepler_vm_metrics.yml
Added 2 tests:
Test idle VM power monitoring metrics are not zero 
Test dynamic VM power monitoring metrics are increasing
> Add basic tests for VM power monitoring metrics

- .zuul.yaml
- ci/use-master-containers.yml
- roles/telemetry_verify_metrics/defaults/main.yml
- roles/telemetry_verify_metrics/tasks/main.yml
- roles/telemetry_verify_metrics/tasks/verify_mariadb_metrics.yml
Depends-On: https://github.com/openstack-k8s-operators/telemetry-operator/pull/658
Mariadb mysql queries file add to tasks
> Alexy metrics

- .zuul.yaml
- ci/report_result.yml
- ci/vars/common.yml
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/252
> [ci] Update report_results to use XML files

- roles/telemetry_verify_metrics/tasks/verify_mariadb_metrics.yml
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/255
Update Polarion Test label in MariaDB tests
> Update Polarion Test label in MariaDB tests

- roles/test_sensubility/tasks/test_health_status.yml
Add number of retries for failing fvt tests
> [test_sensubility] Increase number of retries on metrics check

- callback_plugins/custom_junit.py
- ci/report_result.yml
- ci/vars/common.yml
Depends-on: https://github.com/openstack-k8s-operators/ci-framework/pull/3045
> [ci] Write the XML files directly to ci-framework-data/tests/

- roles/telemetry_verify_metrics/tasks/main.yml
- roles/telemetry_verify_metrics/tasks/verify_ceilometer_central_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_ceilometer_compute_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_ceilometer_ipmi_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_kepler_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_kepler_vm_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_ksm_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_node_exporter_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_openstack_network_exporter_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_podman_exporter_metrics.yml
- roles/telemetry_verify_metrics/tasks/verify_rabbitmq_metrics.yml
Remove all the RHOSO-XXX IDs from the FVTs
Removed all test_id vars in all playbooks under roles/telemetry_verify_metrics tests
> Remove test_id vars under telemetry_verify_metrics

- ci/logging_tests_computes.yml
> Remove unneeded ids from fvt tests
