infrawatch/feature-verification-tests

- README
- callback_plugins/custom_logger.py
- stf_functional_tests.yml
Update to @lnatapov's  change to log test summary to file.
This approach uses an ansible callback and produces the same output format.
The file is currently placed in the directory which the playbook is called from.
The callback can be used either by passing a config variable::
ANSIBLE_CALLBACK_WHITELIST=custom_logger ansible-playbook -i `infrared workspace inventory` stf_functional_tests.yml
or by including ``callback_whitelist = custom_logger`` in the [defaults] section of the ansible.cfg
> Add summary log file for tests

- stf_functional_tests.yml
OSP13 uses docker instead of podman, this change adds an alias for root user so `podman` maps to `docker`, so CI can run against OSP13 and OSP16 without separate branches needed to resolve the differences.
> Add alias to allow running tests in OSP13

- README
- README.rst
- defaults/main.yml
- stf_functional_tests.yml
- tasks/test_collectd.yml
- tasks/test_qdr.yml
Split the tests into separate task files so that they can be imported by other
testing tools.
Currently, it is planned that the collectd_config[1] and tripleo_collectd[2]
roles will use this in molecule and CI testing.
Later on, it'll be used to test other components intended for use with tripleo.
Allowing the changing of container names make it more re-usable as well.
There's a bit of a hack in stf_functional_tests.yaml to let the "default" vars be passed to  the tests; this is intended to be temporary and will be fixed later, it is in place at the moment to keep the behaviour of the stf_functional_tests.yaml identical to before.
[1] https://github.com/infrawatch/collectd-config-ansible-role
[2] https://github.com/infrawatch/tripleo-collectd-ansible-role
> Reorg tests and add config to all reusing of the tests

- tasks/test_collectd.yml
Some metrics produce more than one value at a time (e.g. rx and tx
values for network/if_octets)
The test will fail when the number of values returned is not one.
This change updates that test to make sure that there is a non-zero
number of values returned.
> [collectd] Update test for metrics collected

- tasks/test_qdr.yml
These tests were failing in our GHA-based CI because it has busybox instead of GNU grep
https://github.com/infrawatch/tripleo-qdr-ansible-role/runs/1689224720#step:5:404
> Add -C to grep commands for busybox compat

- roles/test_snmpTraps/tasks/main.yml
The default alertmanager route we describe in the docs requires 30s of disruption at minimum before it will send an alert. We don't want to sleep for long because the pod may be able to restart and transmit some data, so we should keep the sleep 1 but increase the loop size to guarantee that this lasts at least 30s.
> Increasing the loop size for snmpTraps test

- default.inv
Long lived STF deployed on QuickLab is not available anymore. 
We deployed a new STF on PSI using stf-v-c and this patch adjusts inv file of functional tests to connect to the new STF.
> Adjusting inv file with credentials of new STF deployed on PSI

- roles/client_side_tests/defaults/main.yml
- roles/client_side_tests/tasks/get_prom_info.yml
- roles/client_side_tests/tasks/test_e2e.yml
- roles/test_alerts/tasks/test_create_an_alert.yml
- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
- roles/test_sensubility/tasks/test_health_status.yml
This change is required in order to match changes in STO where we will stop allowing http basic auth for access from grafana to prometheus, and use an oauth token from a new restricted service account instead.
Depends-On: https://github.com/infrawatch/service-telemetry-operator/pull/549/
> Use OAuth token instead of http basic auth for prometheus access

- ci/vars-functional-test.yml
ci-framework allows for hooks to be defined as multiple hooks in a list, or single hooks in their own parameters.
If two separate vars files (passed to cifmw_extras) define the same hook, then one gets overwritten by the other, depending on the order in which the vars files are imported.
Using the "single hook in its own parameter" method of defining the hook prevents this issue.
> [zuul] Use alternative syntax for defining hooks

- ci/vars-functional-test.yml
ci-framework allows for hooks to be defined as multiple hooks in a list, or single hooks in their own parameters.
If two separate vars files (passed to cifmw_extras) define the same hook, then one gets overwritten by the other, depending on the order in which the vars files are imported.
Using the "single hook in its own parameter" method of defining the hook prevents this issue.
> [zuul] Use alternative syntax for defining hooks (#102)

- roles/telemetry_logging/tasks/journal_tests.yml
- roles/telemetry_logging/tasks/main.yml
* Update var names: identifiers_list -> journal_list
* Replace "| wc" in shell with check for stdout_lines | length in failure conditions
* Add additional failure conditions
* if there are no journal entries, the rc is 0 and the number of lines 1 ("-- No entries --")
* there should be nothing output to stderr
* fix syntax error on multi-line command (add |)
* use "become: true", to give the task the escalated priviledges it needs to access the journal
* rename the task to include the test ID, so that the custom_logger plugin logs the test result
> [telemetry_logging] Update the journal tests

- ci/report_result.yml
grep fails when there are no lines matched (rc=1), but also when the file doesn't exist (rc>1). This change updates the check so that the error is reported properly.
> [report_result] Update check for failed tests

- callback_plugins/custom_logger.py
- ci/ansible.cfg
Allow configuration via the env var CUSTOM_PLUGIN_OUTPUT_DIR or the ini file using the "output_dir" option in the "custom_logger" section.
NOTE: For paths, a leading "/" is needed when using env vars so that the path is read as an absolute path.
> [custom_logger] Make the output dir configurable

- stf_functional_tests.yml
The observability strategy role should not be run in stf_funtional_tests
Depends-On: https://github.com/openstack-k8s-operators/openstack-operator/pull/1115
> The observability strategy role should not be run in stf_funtional_tests

- ci/patch-openstack-versions.yaml
- ci/run_autoscaling_osp18.yml
- roles/telemetry_autoscaling/tasks/creating_stack.yml
- roles/telemetry_autoscaling/tasks/post_teardown.yml
- roles/telemetry_autoscaling/tasks/test_autoscaling.yml
- roles/telemetry_autoscaling/templates/instance.yaml.j2
- roles/telemetry_autoscaling/templates/template.yaml.j2
Latest updates to ceilometer and sg-core allow us to use server_group for autoscaling server grouping instead of the server_name_prefix. Unfortunately this functionality is only on ceilometer master, so we need to patch the openstackversions to use that. Because ceilometer-central-agent is running on the compute nodes, we need to redeploy the dataplane after patching the openstackversions.
I also found a few TODOs and other places that I thought I can enhance a little. I included that as well.
> Switch to server_group for 18 autoscaling

- roles/telemetry_verify_metrics/defaults/main.yml
I think the bug should be fixed now.
> Enable NodeExporter tests in metric-verification

- .zuul.yaml
Don't run tests on changes to the roles that aren't run
> [zuul] Update irrelevant files for osp18 tests

- roles/client_side_tests/tasks/test_e2e.yml
- roles/test_alerts/tasks/test_create_an_alert.yml
- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
- roles/test_collectd/tasks/main.yml
- roles/test_metrics_retention/tasks/main.yml
- roles/test_observability_strategy/tasks/main.yml
- roles/test_qdr/tasks/main.yml
- roles/test_sensubility/tasks/main.yml
- roles/test_sensubility/tasks/test_health_status.yml
- roles/test_snmp_traps/tasks/main.yml
- roles/test_verify_email/tasks/main.yml
The tasks were previously renamed to just be the test id, due to limitations in the custom_logger callbaack plugin. This was addressed, and the test_report_result reports in the correct format now, so the names can be reverted.
This makes reports more grokable, since the summary_result.log contains a list of the passed/failed tests with the task names.
> Rename tasks to have test id and description

- roles/test_alerts/tasks/get_observability_api.yml
- roles/test_alerts/tasks/main.yml
- roles/test_alerts/tasks/test_create_an_alert.yml
- roles/test_verify_email/tasks/main.yml
Depending on the observability strategy that STF uses, observability components will be installed from community or Red hat sources. These crate the same CRDs, but with different APIs e.g.
prometheusrules.monitoring.rhobs vs
prometheusrules.monitoring.coreos.com. An apiVersion needs to be set when creating these resources during the tests, and the tests will fail if the correct version is not available.
The test_alerts role will select which observability APIs to use based on which observability_straegy is set. The tests will also explicitly use the fully qualified name of the objects using ``oc get``.
The following roles are updated:
* test_alerts
* test_verify_email
> Determine API versions based on observability strategy

- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
The prometheus container in the prometheus-default pod no longer has wget included.
The equivalent curl command is used instead.
> [test_alerts] Update the command for checking the alert in alert manager

- ci/run_autoscaling_osp18.yml
- ci/run_verify_metrics_osp18.yml
The tests should be run with ignore_errors: true in order to run all the tests. Without this, the tests will only run until the first failing test. This change is inline with the way the other test roles are included
> [ci] Update the test playbooks to ignore errors in tests

- roles/telemetry_autoscaling/tasks/creating_stack.yml
There is not enough time for that metric to be scraped. We should add a retry to the task.
Worst case scenario the  metric can take 2 minutes to appeara.
> Adding retry to the ceilometer_cpu metric task

- roles/test_alerts/tasks/test_create_an_alert.yml
- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
- roles/test_snmp_traps/tasks/main.yml
- roles/test_verify_email/tasks/main.yml
This let the cleanup always be done, even when there are test failures.
> Add block/always to tests to separate test procedure from cleanup

- roles/test_verify_email/tasks/main.yml
The updates also provides more info when debugging since the output isn't "filtered" through grep
> [test_verify_email] Add retry/until when checking for alertmanager logs

- roles/test_sensubility/tasks/test_health_status.yml
The test should fail when there are no lines matched
> [test_sensubility] Update the checks to fix the conditions

- roles/test_alerts/tasks/test_create_an_alert.yml
- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
* Update the alarm to use "fvt-tests" in the name and FVT_TESTING in the alarm description so we can identify the alarm created by each test
* Delete the prometheusrule when the test is over
* Wait until the rule is deleted
> [test_alerts] Pre-create and post-delete PrometheusRules

- ci/logging_tests_controller.yml
- roles/common/README.md
- roles/common/tasks/file_tests.yml
- roles/common/tasks/main.yml
- roles/common/tasks/service_tests.yml
OSPRH-9659
This covers adding the tasks from https://github.com/infrawatch/feature-verification-tests/pull/123 into a spearate PR, which will include:
Update roles/common/tasks/main.yml
Add roles/common/tasks/service_tests.yml
Add roles/common/tasks/file_tests.yml
Add service_tests and file_tests to the ci/logging* playbook
Update the README file to document the configuration options
> Add service and file tests to the logging job

- ci/logging_tests_controller.yml
In FR1 we stopped using the dataplane-operator. It was merged into the openstack-operator, so we can't expect it to be running. Check that openstack-operator is running instead.
Depends-On: https://github.com/openstack-k8s-operators/telemetry-operator/pull/572
> Fix logging after update to CLO 6

- roles/test_snmp_traps/tasks/main.yml
This ensures that the prom creds are available for the test.
Previously, the tests suites running this would "assume" that the vars were already set.
> [test_snmp_traps] Add a task to get prom creds at the start of the test

- roles/test_snmp_traps/tasks/main.yml
Use rescue to provide additional information when the test fails
This provides additional debug information in the ansible log, making it more convenient to identify the reason for a failure
> [test_snmp_traps] Add debug after a failure

- .zuul.yaml
- ci/run_autoscaling_osp18.yml
- ci/use-master-containers.yml
- ci/vars-use-master-containers.yml
- roles/telemetry_autoscaling/tasks/test_autoscaling.yml
If we manage to change the openstackversions as needed before the dataplane gets deployed the first time, we don't need to redeploy it later. This could speed up the job by like 30 minutes as well as fix our current issues.
> Move container image patch to post_ctlplane hook

- roles/common/tasks/file_tests.yml
failed_when uses and for list items, and fails only when all conditions are met
The task should fail when any of the conditions are met.
> [common] Fix failure condition in file test

- .ansible-lint
- roles/common/tasks/container_test.yml
- roles/common/tasks/cr_tests.yml
- roles/common/tasks/crd_tests.yml
- roles/common/tasks/endpoint_tests.yml
- roles/common/tasks/file_tests.yml
- roles/common/tasks/main.yml
- roles/common/tasks/manifest_tests.yml
- roles/common/tasks/pod_tests.yml
- roles/common/tasks/project_tests.yml
- roles/common/tasks/service_tests.yml
- roles/common/tasks/subscription_tests.yml
- roles/telemetry_logging/tasks/journal_tests.yml
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/204
> Rename tasks for XML reporting

- ci/logging_tests_controller.yml
This comes from the original logging job PR: https://github.com/infrawatch/feature-verification-tests/pull/113
The names of the completed pods that are expected to exist have been updated
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/213
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/181
> Add pod tests for Completed pods in the OpenStack namespace

- ci/logging_tests_controller.yml
- roles/common/README.md
- roles/common/defaults/main.yml
The test checks for the various openstack endpoints that we expect to exist
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/181
> [ci] Add endpoint tests to the logging job

- .zuul.yaml
The projects should contain "github.com/" prefix.
> Change required projects

- roles/common/README.md
- roles/telemetry_verify_metrics/README.md
- roles/telemetry_verify_metrics/defaults/main.yml
- roles/telemetry_verify_metrics/tasks/main.yml
- roles/telemetry_verify_metrics/tasks/verify_openstack_network_exporter_metrics.yml
Add tests for operator of openstack-network-exporter
> feature_tests: add openstack-network-exporter feature tests

- ci/logging_tests_computes.yml
- roles/common/tasks/container_test.yml
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/181
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/204
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/217
Depends-On: https://github.com/openstack-k8s-operators/telemetry-operator/pull/621
> Add container tests to logging job

- .zuul.yaml
if we have the files listed in the jobs, then any change in telemetry-operator repo will not trigger them.
so I moved the files listed to the project to make the filtering happen in the scope of feature-verification repo.
its being tested in : https://github.com/openstack-k8s-operators/telemetry-operator/pull/644 
and in https://github.com/infrawatch/feature-verification-tests/pull/226
> [Zuul] Update files_list to be in the project

- roles/telemetry_logging/tasks/journal_tests.yml
failed_when and assert use `and` for for list items, and only fails/passes when all conditions are met.
Currently, failed_when is used to trigger a test failure in the journal tests, however, it is implemented incorrectly, since a list is used, and the task will only fail if all conditions are met. This is incorrect, the test should fail if any of the failure conditions are met.
Using assert instead of failed_when means the test will fail if any of the conditions are not met, which is the expected and correct behaviour.
This change switches to using assert, and check for the complementary conditions.
Using assert also allows for some verbose fail messages to aid in debugging.
> [telemetry_logging] Fix failure condition in journalctl

- roles/telemetry_autoscaling/tasks/test_autoscaling.yml
Fail if there's not an instance already created.
Also removes the "wc -l" portion of the shell
commands and uses stdout_lines | length filter
> [autoscaling] Update initial test for number of instances

- roles/telemetry_verify_metrics/tasks/main.yml
- roles/telemetry_verify_metrics/tasks/verify_rabbitmq_metrics.yml
The correct kind from FR2 forwards is "rabbitmqs". See https://github.com/infrawatch/feature-verification-tests/pull/232#discussion_r1977072434 for more context.
> [OSPRH-14451] Change rabbitmq kind to "rabbitmqs"

- .zuul.yaml
Why do we need this PR?
The autoscaling job is not called autoscaling upstream.
The `functional-tests-on-osp18` job should be updated to match the pattern for the other  fvt jobs i.e. `functional-autoscaling-tests-osp18`
NOTE: This change affects feature-verification-tests as well as telemetry-operator.
Depends-On: https://github.com/infrawatch/feature-verification-tests/pull/252
> OSPRH-13452: Update functional-tests-on-osp18 to functional-autoscaling-tests-osp18 to match the fvt job name pattern

- .zuul.yaml
- ci/vars-functional-test.yml
- ci/vars-graphing-test.yml
- ci/vars-logging-test.yml
- ci/vars-metric-verification-test.yml
This approach runs the FVTs before tempets and then collects the results after running test-operator This means that the tempest tests will trigger a failure if they fail, and the FVTs will trigger a failure only after the tempest tests are run, which means that the results are reported as expected.
This will work for github-check pipeline and the component pipeline. However, this approach may not be usable with the unified jobs.
> [ci] Try to combine the FVT and tempest

- .zuul.yaml
- ci/vars-functional-test.yml
- ci/vars-graphing-test.yml
- ci/vars-logging-test.yml
- ci/vars-metric-verification-test.yml
* [ci] Try to combine the FVT and tempest
This approach runs the FVTs before tempest and then collects the results after running test-operator This means that the tempest tests will trigger a failure if they fail, and the FVTs will trigger a failure only after the tempest tests are run, which means that the results are reported as expected.
This will work for github-check pipeline and the component pipeline. However, this approach may not be usable with the unified jobs.
This change adds a tempest config to the logging, graphing, metrics-verification tests.
> [ci] Try to combine the FVT and tempest (#256)

- ci/run_graphing_test.yml
This PR wants to remove the `dashboardsEnabled` applied in the `Graphing Console UI tests` at [run_graphing_test.yml](https://github.com/MiguelCarpio/feature-verification-tests/blob/master/ci/run_graphing_test.yml) in the [functional-graphing-tests-osp18](https://github.com/infrawatch/feature-verification-tests/blob/00b0d3996e190d386205d06ffd1f57818f37cf04/.zuul.yaml#L108C11-L108C42) job, because dashboards are already enabled in the parent [telemetry-operator-multinode-autoscaling](https://github.com/openstack-k8s-operators/telemetry-operator/blob/a2d55f55d5da62bf0b36eea254c44443c56036a1/zuul.d/projects.yaml#L2) job by the PR   https://github.com/openstack-k8s-operators/telemetry-operator/pull/673
Depends-On: https://github.com/openstack-k8s-operators/telemetry-operator/pull/673
> OSPRH-15988: Remove Enable Graphing at graphing test

- roles/common/defaults/main.yml
- roles/telemetry_logging/defaults/main.yml
The *test_id var was set for the common and telemetry_logging roles previously, so that the tests would be reported as passed/failed by custom_logger
Since report_result was updated to use XML files to determine failure, the test ID does not need to be set.
This change adds a default value for these vars, so that we can start removing the vars from test configs.
> Set default values for *_test_id vars

- .zuul.yaml
It runs the same tests as autoscaling-fvt, so can become an alias.
In the future, it may select a subset of tests to run via some var, but for now is the same as the autoscaling-fvt job
> [zuul] Re-parent the verify-metrics job

- roles/test_alerts/tasks/test_create_an_alert.yml
- roles/test_alerts/tasks/test_creating_a_standard_alert_route_in_alert_manager.yml
- roles/test_sensubility/tasks/test_health_status.yml
- roles/test_snmp_traps/tasks/main.yml
- roles/test_verify_email/tasks/main.yml
The issue may have been caused by the observability strategy tests causing both community and redhat monitoring components to be installed and shadowing the monitoring component definitions (prom, alertmanager, etc)
> Fix functional tests failures for STF tests

- .github/workflows/lint.yml
- meta/runtime.yml
ansible-community/ansible-lint-action is no longer available. 
Using ansible/ansible-lint instead.
> [GHA] Update the ansible-lint actions used

- ci/patch-openstack-versions.yaml
The centos9 images are no longer building because of the out-dated python version
> [zuul] Use centos-10 images for master versions

- roles/telemetry_autoscaling/tasks/configure_heat.yml
- roles/telemetry_autoscaling/tasks/creating_stack.yml
- roles/telemetry_autoscaling/tasks/main.yml
- roles/telemetry_autoscaling/tasks/test_autoscaling.yml
- roles/telemetry_graphing/tasks/cypress_test.yml
- roles/telemetry_graphing/tasks/verify_url.yml
Removed all rhosoid's from roles/telemetry_autoscaling/tasks
> Remove unneeded test IDs from FVTs

- .github/workflows/check_plugin.yml
- ci/ansible.cfg
- ci/report_result.yml
- ci/vars-functional-test.yml
- ci/vars-graphing-test.yml
- ci/vars-logging-test.yml
- ci/vars-metric-verification-test.yml
- roles/telemetry_graphing/vars/main.yml
The logs are output to the expected location, and don't need to be copied twice.
> [ci] Remove the extra copy of XML file from hooks

- .zuul.yaml
- roles/telemetry_verify_metrics/README.md
- roles/telemetry_verify_metrics/defaults/main.yml
- roles/telemetry_verify_metrics/tasks/main.yml
- roles/telemetry_verify_metrics/tasks/verify_ceilometer_volume_pool_metrics.yml
To check volume pool metrics, we need a correct environment configured with a storage backend - in this case ceph. The job takes abet 20 minutes longer than our usual jobs, so it was decided to run it as part of the periodic pipeline instead of running it with each PR in the check pipeline.
> Add periodic job with volume pool metrics tests

- .zuul.yaml
- ci/run_functional_tests.yml
- ci/vars-graphing-test.yml
- ci/vars-logging-test.yml
The logging tests were updated to run unconditionally in PR#275. 
This is a problem when logging is not deployed as the tests fail (which is expected). This change re-adds the previous logging vars file, so that jobs can enable/disable logging tests as before.
> [ci] Re-add logging vars

- roles/telemetry_verify_metrics/tasks/verify_ceilometer_volume_pool_metrics.yml
The volume metrics don't have a project label, so older versions of the python-observabilityclient aren't able to show the metrics unless we use the --disable-rbac.
> Add disable-rbac to volume metric tests
